<!DOCTYPE html>
<html lang="en">
<head>
    <title>Matrix Admin</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/back/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/back/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="/back/css/fullcalendar.css" />
    <link rel="stylesheet" href="/back/css/matrix-style.css" />
    <link rel="stylesheet" href="/back/css/matrix-media.css" />
    <link href="/back/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="/back/css/jquery.gritter.css" />
</head>