<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/23/023
 * Time: 9:46
 */

namespace Dldh\Modules\Backend\Controllers;
use Dldh\Models\Config;
use Phalcon\Mvc\Controller;

class SystemController extends ControllerLoginBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){
        $list=\Dldh\Models\Config::find([
            'conditions' => 'hidden = :hidden:  order by id asc',
            'bind' => [
                'hidden' => 0
            ],
        ])->toArray();
        $this->view->setVar('list', $list);
    }
    public function updateAction(){
        try{
            if($this->request->getPost()){
                  $id=$this->request->getPost('id');
                  $value=$this->request->getPost('value');
                  $txt=$this->request->getPost('txt');
                  if(   $id>0){
                      if(''== $value or ''== $txt){
                          exit($this->ajax_return('不能为空','0'));
                      }
                      $con=new \Dldh\Models\Config();

                      $con->id=$id;
                      $con->value=$value;
                      $con->txt= $txt;
                      $return=$con->save();

                  /*

                      */
                      $profiles = $this->di->get('profiler')->getProfiles();
                      exit($this->ajax_return($profiles,'1'));
                      if($return){
                          exit($this->ajax_return('修改成功','1'));
                      }else{
                          exit($this->ajax_return('修改失败','0'));
                      }
                  }else{
                      exit($this->ajax_return('非法请求','0'));
                  }
            }else{
                exit($this->ajax_return('非法请求','0'));
            }
        }catch (\Exception $e){
            $this -> write_exception_log($e);
            //$this -> flashSession -> error($e -> getMessage());
            exit($this->ajax_return('发生错误','0'));
        }
    }

}