<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/23/023
 * Time: 9:46
 */

namespace Dldh\Modules\Backend\Controllers;
use Dldh\Models\Config;
use Phalcon\Mvc\Controller;
use Phalcon\Mvc\Router\Route;


class SystemController extends ControllerLoginBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @Get("/listss")
     */

    public function indexAction(){
        $list=\Dldh\Models\Config::find([
            'conditions' => 'hidden = :hidden:  order by id asc',
            'bind' => [
                'hidden' => 0
            ],
        ])->toArray();
        $this->view->setVar('list', $list);
    }
    public function updateAction(){
       try{
            if($this->request->getPost()){
                  $id=$this->request->getPost('id');
                  $value=$this->request->getPost('value');
                  $txt=$this->request->getPost('txt');
                  if(   $id>0){
                      if(''== $value or ''== $txt){
                          exit($this->ajax_return('不能为空','0'));
                      }

                      $con=    \Dldh\Models\Config::findFirst('id='.$id);
                      $con->value=$value;
                      $con->txt= $txt;
                      $return=$con->save();

                      if($return){
                          exit($this->ajax_return('修改成功','1'));
                      }else{
                          exit($this->ajax_return('修改失败','0'));
                      }
                  }else{
                      exit($this->ajax_return('非法请求','0'));
                  }
            }else{
                exit($this->ajax_return('非法请求','0'));
            }
        }catch (\Exception $e){

            exit($this->ajax_return('发生错误','0'));
        }

    }


    public function usersAction(){
       // var_dump(\Dldh\Models\User::find());
       // exit;
           $this->view->setVar('list',\Dldh\Models\User::find() );
    }

    public function userenableAction(){
        try{
            $data=$this->request->getPost();
            if($data){
                $id=$data['id'];

                $usr=\Dldh\Models\User::findFirst('id='.$id[0]);

                if($usr){
                    $usr->setEnabled($data['enable']);
                    $re=$usr->save();
                    /* echo $this->di->get('profiler')->getLastProfile()->getSQLStatement();
                    exit;*/
                    if($re){
                        exit($this->ajax_return( '修改成功',1 ));
                    }
                    exit($this->ajax_return( '修改失败',0 ));

                }else{
                    exit($this->ajax_return( '无此记录',0 ));
                }
            }else{
                exit($this->ajax_return( '非法请求',0 ));
            }

        }catch (\Exception $e){
            exit($this->ajax_return( '发生错误',0 ));
        }
    }

}